### PR TITLE
piping electron stdout and stderr to debug calls

### LINKED ISSUE #421: swallowing electron errors
we're currently swallowing errors, making debugging nightmare timeouts incredibly difficult:

**timeout.js**

```js

var ms = require('ms');
var Nightmare = require('./')

var n = new Nightmare;
n.goto('http://yahoo.com').end(function() {
  console.log('=)')
  process.exit(0)
});

setTimeout(function() {
  console.error('timeout')
  process.exit(1)
}, ms('30s'))
```

**output**:

```
$ DEBUG=nightmare* node timeout
  nightmare queueing action "goto" for http://yahoo.com +17ms
  nightmare running +3ms
timeout
```

----

running `dist/electron` directly yields:

```
$ node_modules/electron-prebuilt/dist/electron lib/runner.js 
node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

... any reason we're not sending this to `stderr`, or at least notifying the user that something went wrong?

### PR DESCRIPTION
**Pull request by rosshinkley**
Fixes #421, at least in part.

Open questions: 

1. Should Nightmare override the environment variable for `ELECTRON_ENABLE_LOGGING`?
2. Should the `nightmare:` namespace be on the debug calls for Electron?

### CODE REVIEW

File: lib/nightmare.js [hunk 1]
```diff
@@ -67,6 +71,14 @@ function Nightmare(options) {
     stdio: [null, null, null, 'ipc']
   });
 
+  this.proc.stdout.on('data', (data) => {
```
Comment (Mr0grog) [inline lib/nightmare.js]: It’s unlikely to be too big a deal, but as a general practice, it’d be a good idea to pipe through `split` or `split2` first—there’s no guarantee otherwise that stuff will come out of the `stdout/stderr` streams as whole lines (could be more or less).

**Comment by Mr0grog** [comment]
> Should Nightmare override the environment variable for ELECTRON_ENABLE_LOGGING

I would say nah. For high-level issues someone is likely to care about (deprecation notices, info about why Electron failed to start, etc.), info gets logged regardless of this env var. It gets pretty verbose if you turn it on. Better to leave that up to a user, I think.

> Should the nightmare: namespace be on the debug calls for Electron?

I’d say nah to this, too, but I don’t really have any good reasoning or a strong case for it.

File: lib/nightmare.js (hunk 1 above)
Comment (rosshinkley) [inline lib/nightmare.js]: Ah, that's a good call.  I'll make the update.

**Comment by rosshinkley** [comment]
> It gets pretty verbose if you turn it on. Better to leave that up to a user, I think.

My thoughts too.  Thought I'd float it just to make sure there wasn't something I missed.

> I’d say nah to this, too, but I don’t really have any good reasoning or a strong case for it.

The best (and possibly only) reason I'd be in favor of leaving it prefixed with `nightmare:` is to maybe simplify `DEBUG`.  However, with your test to catch deprecation warnings, I'm not sure there's a case to be made.
